부록 B 텐서(배열) 연산

In [ ]:
# 셋업
import numpy as np
import tensorflow as tf
import torch

In [ ]:
# shape 확인

a = np.array(1)   # 스칼라
print(f"{a.shape} \n")

b = np.array([1, 2, 3, 4, 5, 6])   # 벡터
print(f"{b.shape} \n")

c = tf.constant([[1, 2, 3], [4, 5, 6]])   # 행렬
print(f"{c.shape} \n")

d = torch.tensor([[[1, 2, 3], [4, 5, 6]]])   # 3차원 텐서
print(d.shape)

() 

(6,) 

(2, 3) 

torch.Size([1, 2, 3])


In [ ]:
# 텐서 변환(텐서플로-넘파이)

a = tf.constant([[1, 2, 3], [4, 5, 6]])
print(a)

b = a.numpy()   # 넘파이 배열로 변환
print(f"\n{b} \n")

c = tf.convert_to_tensor(b)   # 텐서로 변환
print(c)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)

[[1 2 3]
 [4 5 6]] 

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [ ]:
# 텐서 변환(파이토치-넘파이)

a = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(f"{a} \n")

b = a.numpy()   # 넘파이 배열로 변환
print(f"{b} \n")

c = torch.from_numpy(b)   # 텐서로 변환
print(c)

d = torch.tensor(b)
print(f"\n{d}")

tensor([[1, 2, 3],
        [4, 5, 6]]) 

[[1 2 3]
 [4 5 6]] 

tensor([[1, 2, 3],
        [4, 5, 6]])

tensor([[1, 2, 3],
        [4, 5, 6]])


In [ ]:
# 인덱싱/슬라이싱(요소 선택)

a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

print(a)
print(a[0])   # 인덱싱(특정 요소 선택)
print(a[5])
print(a[-1])
print(a[:5])   # 슬라이싱(특정 범위의 요소 선택)
print(a[5:])
print(f"{a[5:-1]} \n")

b = np.array([[1, 2, 3], [4, 5, 6], [7, 8,9]])

print(b)
print(b[0])
print(b[2])
print(b[0][1])
print(b[0, 1])
print(b[1][1:])

[0 1 2 3 4 5 6 7 8 9]
0
5
9
[0 1 2 3 4]
[5 6 7 8 9]
[5 6 7 8] 

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3]
[7 8 9]
2
2
[5 6]


In [ ]:
# zeros(/ones(0/1 배열 생성)

a = np.zeros(2)   # 모든 요소가 0인 배열 생성
print(a)

b = np.ones((2, 3))   # 모든 요소가 1인 배열 생성
print(f"{b} \n")

c = tf.zeros(2)
print(c)

d = tf.ones((2, 3))
print(d)

e = torch.zeros(2)
print(f"\n{e}")

f = torch.ones((2, 3))
print(f)

[0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]] 

tf.Tensor([0. 0.], shape=(2,), dtype=float32)
tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)

tensor([0., 0.])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [ ]:
# random(난수 생성)

np.random.seed(77)
a = np.random.randint(1, 10, size=(3, 2))   # 랜덤 정수
print(f"{a} \n")

b = np.random.randn(2, 3)   # 정규 분포
print(f"{b.round(2)} \n")

c = np.random.normal(size=(2, 3))   # 정규 분포
print(f"{c.round(2)} \n")

d = np.random.uniform(size=(2, 3))   # 균등 분포
print(f"{d.round(2)} \n")

e = tf.random.normal(shape=(3, 2), mean=0, stddev=1)
print(f"{e.numpy().round(2)} \n")

f = tf.random.uniform(shape=(3, 2), minval=1, maxval=10)
print(f"{f.numpy().round(2)} \n")

g = torch.rand(3, 2)
print(g.numpy().round(2))

[[8 5]
 [5 6]
 [9 1]] 

[[ 0.77 -0.32  0.81]
 [ 1.07  1.1  -0.03]] 

[[-1.32 -0.33  0.18]
 [ 0.11  0.12 -0.23]] 

[[0.32 0.86 0.96]
 [0.98 0.66 0.46]] 

[[-0.17  0.12]
 [-0.26  0.12]
 [-0.03 -0.18]] 

[[5.97 8.13]
 [9.43 2.46]
 [2.81 6.43]] 

[[0.29 0.82]
 [0.09 0.3 ]
 [0.29 0.51]]


In [ ]:
# transpose(전치 행렬)

a = np.array([[1, 2, 3], [4, 5, 6]])
print(f"{a} \n")

b = a.transpose(1, 0)
print(f"{b} \n")

c = a.T
print(f"{c} \n")

d = tf.transpose(a)
print(d)

e = torch.transpose(torch.tensor(a), 0, 1)
print(f"\n{e}")

[[1 2 3]
 [4 5 6]] 

[[1 4]
 [2 5]
 [3 6]] 

[[1 4]
 [2 5]
 [3 6]] 

tf.Tensor(
[[1 4]
 [2 5]
 [3 6]], shape=(3, 2), dtype=int64)

tensor([[1, 4],
        [2, 5],
        [3, 6]])


In [ ]:
# matmul(행렬곱)

a = np.array([[1, 2], [3, 4]])
print(f"{a} \n")

b = np.array([[5, 6], [7, 8]])
print(f"{b} \n")

c = a * b   # 원소 별 곱셈
print(f"{c} \n")

d = np.dot(a, b)   # 내적
print(f"{d} \n")

e = np.matmul(a, b)   # 행렬곱
print(f"{e} \n")

f = tf.matmul(a, b)
print(f)

g = torch.matmul(torch.tensor(a), torch.tensor(b))
print(f"\n{g}")

[[1 2]
 [3 4]] 

[[5 6]
 [7 8]] 

[[ 5 12]
 [21 32]] 

[[19 22]
 [43 50]] 

[[19 22]
 [43 50]] 

tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int64)

tensor([[19, 22],
        [43, 50]])


In [ ]:
# argmax(최대값 인덱스)

a = np.array([[1, 3, 5], [7, 9, 2], [4, 6, 8]])
print(f"{a} \n")

b = np.argmax(a, axis=0)   # 최대값의 인덱스
print(f"{b} \n")

c = np.argmax(a, axis=1)
print(f"{c} \n")

d = np.argmax(a, axis=-1)
print(f"{d} \n")

e = np.max(a, axis=0)   # 최대값
print(f"{e} \n")

f = np.max(a, axis=1)
print(f)

[[1 3 5]
 [7 9 2]
 [4 6 8]] 

[1 1 2] 

[2 1 2] 

[2 1 2] 

[7 9 8] 

[5 9 8]


In [ ]:
# reshape(shape 변환)

a = np.arange(1, 13)
print(f"{a} \n")

b = a.reshape(3, 4)
print(f"{b} \n")

c = a.reshape(-1)
print(c)

[ 1  2  3  4  5  6  7  8  9 10 11 12] 

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
# view(shape 변환)

a = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])
print(f"{a} \n")

b = a.view(3, 2)
print(f"{b} \n")

c = a.view(-1)
print(f"{c} \n")

d = a.view(1, -1)
print(d)

tensor([[1, 2, 3],
        [4, 5, 6]]) 

tensor([[1, 2],
        [3, 4],
        [5, 6]]) 

tensor([1, 2, 3, 4, 5, 6]) 

tensor([[1, 2, 3, 4, 5, 6]])


In [ ]:
# squeeze/unsqueeze(차원 축소/확대)

a = torch.tensor([[[1, 2, 3], [4, 5, 6]]])
print(f"{a} \n")

b = a.squeeze()   # 차원 축소
print(f"{b} \n")

c = b.unsqueeze(dim=0)   # 차원 확대
print(c)

tensor([[[1, 2, 3],
         [4, 5, 6]]]) 

tensor([[1, 2, 3],
        [4, 5, 6]]) 

tensor([[[1, 2, 3],
         [4, 5, 6]]])


In [ ]:
# item(스칼라 값 추출)

a = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(f"{a} \n")

b = a[1][2]   # 텐서
print(b)

c = a[1][2].item()   # 텐서에서 스칼라 값 추출
print(f"\n{c}")

tensor([[1, 2, 3],
        [4, 5, 6]]) 

tensor(6)

6


In [ ]:
# concatenate/stack(배열 결합)

a = np.arange(1, 6).reshape(-1)
print(f"{a} \n")

b = np.arange(1, 10, 2).reshape(-1)
print(f"{b} \n")

c = np.concatenate((a, b))   # 배열 연결
print(f"{c} \n")

d = np.stack((a, b))   # 새로운 축으로 배열 쌓음
print(f"{d} \n")

e = list(zip(a, b))    # 튜플로 묶어 리스트 생성
print(f"{e} \n")

f = dict(zip(a, b))    # 딕셔너리 생성
print(f)

[1 2 3 4 5] 

[1 3 5 7 9] 

[1 2 3 4 5 1 3 5 7 9] 

[[1 2 3 4 5]
 [1 3 5 7 9]] 

[(1, 1), (2, 3), (3, 5), (4, 7), (5, 9)] 

{1: 1, 2: 3, 3: 5, 4: 7, 5: 9}
